import Head from 'next/head'
import { Button } from '../components/ui/button'
import { BaseContainer } from '../components/ui/container'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next+Stitches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BaseContainer>
        <main>
          <Button color="green">Hello, World</Button>
          <Button color="gray">Hello, World</Button>
        </main>
      </BaseContainer>
    </div>
  )
}
